### ISSUE TITLE
How to integrate KaTeX into memory card application

### ISSUE THREAD

**Issue by vinodpkd** [bradtraversy/vanillawebprojects#10]
How to integrate KaTeX into memory card application so that I can include mathematical equations to flash cards.

https://github.com/KaTeX/KaTeX

I have tried from my side :

https://stackoverflow.com/questions/60087885/how-to-integrate-katex-into-memory-card-application

**Comment by florinpop17** [comment]
Please post these type of questions on QA section on Udemy. We're keeping these issues specifically with the repository.
