### ISSUE TITLE
[Proposal] Refactor formatMoney function in project no. 5

### ISSUE THREAD

**Issue by jakubfiglak** [bradtraversy/vanillawebprojects#13]
Hello there, I suggest using Intl API instead of the regex version. The function would then look like this: 

`// Format number as money
function formatMoney(amount) {
  return new Intl.NumberFormat('en-EN', {
    style: 'currency',
    currency: 'USD',
  }).format(amount);
}`

Not a big deal, but it looks much cleaner to me and I've just learned about it a couple days ago so I'm bragging about it 👯‍♂

**Comment by bradtraversy** [comment]
Thanks!
