### ISSUE TITLE
API is not working

### ISSUE THREAD

**Issue by bilalkaya** [bradtraversy/vanillawebprojects#25]
randomuser.me is not reachable so code is not working. (date 17.03.2020)

**Comment by agepoor** [comment]
Hi, I had the same problem yesterday. I decided to just use a different API with the data from https://covid19api.com/ . I changed a few things, but all the methods are covered.
[Corona Array Methods](https://github.com/agepoor/corona-array)

**Comment by bilalkaya** [comment]
I also used a different api but today https://randomuser.me/ website is reachable and code is working properly.
