### ISSUE TITLE
[Hangman] - after loosing game entering letters is still possible

### ISSUE THREAD

**Issue by swiecaJS** [bradtraversy/vanillawebprojects#3]
Steps to reproduce

- enter https://vanillawebprojects.com/projects/hangman/
- lose a game
- try entering letters
- you can still win the game

![image](https://user-images.githubusercontent.com/12431424/73449747-2aad1c00-4364-11ea-92d2-bd6b2e2f0c61.png)

**Comment by bradtraversy** [comment]
Thank you...fixed by adding a playable flag
